name: postgres

services:
  postgres:
    image: postgres:16
    container_name: postgres-learning
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "55432:5432"
    volumes:
      - postgres_datasara:/var/lib/postgresql/data

volumes:
  postgres_datasara:
